update

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,39 +1,33 @@
 #!/usr/bin/env bash
-# Configures a new ubuntu machine by installing
-# Nginx where it should be listening on port 80
-# Serve a page that would return a Hello World string
-#
+# Configures a new Ubuntu machine by installing Nginx
+# Nginx should be listening on port 80 and serving a "Hello World" page
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+set -euo pipefail
 
-echo -e "\nSetting up some minor stuff.\n"
+echo "Updating and installing Nginx..."
+sudo apt-get update -y -qq
+sudo apt-get install nginx -y
 
-# starting nginx service
+echo "Setting up Nginx..."
 sudo service nginx start
 
-# allowing nginx on firewall
+# Allow Nginx through the firewall
 sudo ufw allow 'Nginx HTTP'
 
-# Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+# Backup default index file
+sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak
 
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
+# Serve a "Hello World" page
+echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
 
-# Creating new index
-echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
+# Configure redirection
+sudo sed -i.bak '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
 
-# Setting up /redirect_me to a youtube video
-sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
+# Configure custom 404 page
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null
+sudo sed -i.bak '/server_name _;/a \\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default
 
-# Set up a 404 page
-echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
-sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
-
-# Restarting nginx
+# Restart Nginx to apply changes
 sudo service nginx restart
 
-echo -e "\nCompleted.\n"
+echo "Nginx installation and configuration completed."
